version: "3.1"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb

    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - backend

  server:
    build: ./server
    depends_on:
      - db
    ports:
      - "8080:3000"
    links:
      - db:db
    networks:
      - backend

networks:
  backend:
    driver: bridge
